# Generated by Django 6.0.4 on 2026-06-25 18:00

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescuerProfile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rescuer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('action_radius_km', models.PositiveSmallIntegerField(default=25)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='helprequest',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RescueParticipation',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_participations', to='core.helprequest')),
                ('rescuer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_participations', to='core.rescuerprofile')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='helprequest',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='help_requests_joined', through='core.RescueParticipation', to='core.rescuerprofile'),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField()),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='core_pushsu_user_id_8f8470_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'endpoint'), name='unique_push_subscription_per_user_endpoint')],
            },
        ),
        migrations.AddConstraint(
            model_name='rescueparticipation',
            constraint=models.UniqueConstraint(fields=('help_request', 'rescuer_profile'), name='unique_rescue_participation_per_request'),
        ),
    ]
